services:
  api:
    build: ./api
    image: dm-api:v1
    environment:
      - PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=app
      - DB_PASSWORD=app
      - DB_NAME=dernier_metro
    ports:
      - "5001:5000"
    volumes:
      - ./api:/app
      - /app/node_modules

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=dernier_metro
    ports:
      - "5433:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data

  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./openapi:/openapi:ro
    ports:
      - "8080:8080"
    depends_on:
      - api
      - postgres

volumes:
  pgdata:
